apiVersion: apps/v1
kind: Deployment
metadata:
  name: cropsense-application-server
  labels:
    app: cropsense-application-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cropsense-application-server
  template:
    metadata:
      labels:
        app: cropsense-application-server
    spec:
      containers:
      - name: cropsense-application-server
        image: cropsense-application-server:0.0.1-SNAPSHOT
        env:
          - name: CROPSENSE_RDB_URL
            valueFrom:
              configMapKeyRef:
                name: cropsense-application-server-configmap
                key: CROPSENSE_RDB_URL
          - name: CROPSENSE_RDB_USER
            valueFrom:
              configMapKeyRef:
                name: cropsense-application-server-configmap
                key: CROPSENSE_RDB_USER
          - name: CROPSENSE_RDB_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: cropsense-application-server-configmap
                key: CROPSENSE_RDB_PASSWORD
        ports:
        - containerPort: 8080
