apiVersion: v1
kind: Service
metadata:
  name: cropsense-application-server-service
spec:
  type: NodePort
  selector:
    app: cropsense-application-server
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8080
      nodePort: 30000