apiVersion: apps/v1
kind: Deployment
metadata:
  name: cropsense-metrics-server-deployment
  labels:
    app: cropsense-metrics-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cropsense-metrics-server
  template:
    metadata:
      labels:
        app: cropsense-metrics-server
    spec:
      containers:
      - name: cropsense-metrics-server
        image: cropsense-metrics-server:0.0.1-SNAPSHOT
        envFrom:
          - configMapRef:
              name: cropsense-metrics-server-configmap
        ports:
        - containerPort: 8080